base_url= "https://f5.maatt.fr"
title= "Falcon 5 wiki"

default_language= "en"

generate_feed= true
feed_filename= "atom.xml"

compile_sass= true

[markdown]
highlight_code= false
render_emoji= true
external_links_target_blank= true